In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.read_csv('trainh.csv')

In [3]:
df.drop(['Dates'], axis=1, inplace=True)

In [4]:
x = df.drop("Category", axis=1)
y = df["Category"]


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

## Neural Network

In [7]:
from sklearn.neural_network import MLPClassifier

In [28]:
nn = MLPClassifier(hidden_layer_sizes=(10, 10, 10, 10,10), max_iter=500)

In [29]:
nn.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [30]:
nn.score(x_train, y_train)

0.5909712121360029

In [31]:
nn.score(x_test, y_test)

0.5895260330656948

In [32]:
from sklearn.metrics import classification_report

In [33]:
pred = nn.predict(x_test)

print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.59      1.00      0.74    155290
          1       0.00      0.00      0.00     23212
          2       0.00      0.00      0.00     16215
          3       0.00      0.00      0.00     52625
          4       0.00      0.00      0.00     16073

avg / total       0.35      0.59      0.44    263415



/home/shafi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
print(confusion_matrix(y_test, pred))

[[155290      0      0      0      0]
 [ 23212      0      0      0      0]
 [ 16215      0      0      0      0]
 [ 52625      0      0      0      0]
 [ 16073      0      0      0      0]]


In [36]:
from sklearn.metrics import log_loss

In [37]:
logmodel_probs = nn.predict_proba(x_test)
score = log_loss(y_test, logmodel_probs)
print(score)

1.1707909637578497
